### PR TITLE
provide feature

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by tarsius** [comment]
ping

**Comment by yyr** [comment]
@tarsius 
Author died
https://plus.google.com/+TomTromey/posts/DFuvYBrh4th

**Comment by tarsius** [comment]
Sad to hear that. Rest in peace.

@yyr thanks for pointing this out to me.

**Comment by tarsius** [comment]
See https://github.com/emacsmirror/p/issues/45.

**Pull request closed without merging**
